### ISSUE TITLE
Preload pages count

### ISSUE THREAD

**Issue by wrbl606** [Neil-Gu/preload_page_view#1]
Hey,
Is it possible to make the PreloadPageView customizable in terms of how many pages will be preloaded? As you mentioned in README currently the value is only 1.
```dart
PreloadPageView.builder(
      itemCount: ...,
      itemBuilder: ...,
      // maybe a property like the one below?
      preloadPagesCount: 3,
      onPageChanged: (int position) {...},
      .....
      controller: PreloadPageController(),
    );
```

**Comment by Neil-Gu** [comment]
Hi Marcin,

Thanks for your reply. I'm glad to see my code could help you guys.

For your question the answer is definitely yes, I also need preload multiple page at my own project in the future. Will take some time to improve this widget in the near future.

**Comment by Neil-Gu** [comment]
Hi Marcin,

As you wish I add `preloadPagesCount`, everything is working well for me.

Please test the new function and close this ticket if it's working well
