### ISSUE TITLE
Negative numbers in preloadPagesCount

### ISSUE THREAD

**Issue by wrbl606** [Neil-Gu/preload_page_view#2]
Hey again,
Do you know what is happening when `preloadPagesCount` is negative? I tried with `preloadPagesCount = -1` and `-3` and in both cases it behaves like I'll just put a `1` - is it desired behavior?

Maybe a negative numbers in `preloadPagesCount` property should throw an error since those are not logically correct?

**Comment by Neil-Gu** [comment]
I set 0 and negative number to 1 when user pass those number to `preloadPagesCount`. I will Think about allow 0 and throw exception when user pass negative number

**Comment by wrbl606** [comment]
0 is correct value so it should be allowed. Exception on negative/null value will be great.
